### ISSUE TITLE
typings.antd.radioGroupMod japgolly react component not generated

### ISSUE THREAD

**Issue by an-tex** [ScalablyTyped/Converter#122]
For the antd library (3.26.12), for the radio components at `typings.antd.radioMod` the corresponding japgolly react components are generated at `typings.antd.components.Radio` and `typings.antd.components.RadioButton`, but there's no component generated for the `RadioGroup`

**Comment by oyvindberg** [comment]
Thanks for the report. Will have a look

**Comment by oyvindberg** [comment]
The issue is that more than one component ends up with the name `Group`.

Workaround is to ignore the one that is currently picked:
```
stIgnore ++= List("antd/lib/input/Group"),
```

I'll need to adjust the heuristics for component name to fix this

**Comment by an-tex** [comment]
Got it, works thanks! I wonder if the component hierarchy could be kept as is? E.g. 
```scala
package typings.antd.components

object Radio {
  def apply(..)

  object Button {
     def apply(...)
  }
  object Group {
     def apply(...)
  }

**Comment by oyvindberg** [comment]
Maybe. It's a bit complex actually.

What we have right now is that nested components receive a name which includes the owner name as a [prefix](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/IdentifyReactComponents.scala#L257), for instance this particular component should have appeared as `RadioGroup`. That's probably easy to fix :+1: 


One facet of the problem is that a component like `Group` is reachable through many paths. This might not be exhaustive:

```
typings.antd.mod.Radio.Group
typings.antd.radioGroupMod.default
typings.antd.radioMod.Group
typings.antd.radioMod.default.Group
typings.antd.radioRadioMod.default.Group
```

Since `Group` has a module of its own, it would end up among the "top-level" components (as opposed to a nested one like you propose) anyway, and I'm not sure if more duplication and nesting will end up less confusing.

**Comment by an-tex** [comment]
Thanks for the clarification! That looks indeed tricky. For now I'm happy though ;) Can't say "great library" often enough!
