### ISSUE TITLE
 Scala.js 1.0.0 breaks libraries with nonexisting modules

### ISSUE THREAD

**Issue by mausamyede** [ScalablyTyped/Converter#131]
With beta5, unable to resolve a module from rsocket-websocket-client npm.
The minimal reproduction is here: [stIssue](https://github.com/mausamyede/stIssue)

**Comment by mausamyede** [comment]
BTW, plugin with scala.js 0.6.x which is sbt-converter06 works perfectly fine as can be verified by changing the plugin version in plugins.sbt.

NB: For sbt-converter06 to work we had to use coursier based sbt-launcher otherwise we get error like: xsbt/JarUtils not found

**Comment by oyvindberg** [comment]
Thanks for the repro. Will have a look:)

**Comment by oyvindberg** [comment]
I minimized it to what looks like a difference in behavior between Scala.js 0.6 and 1.0.
```scala
object Main {
  @JSImport("asddsaasd", JSImport.Default)
  @js.native
  class Parent extends js.Object

  @JSImport("rsocket-websocket-client", JSImport.Default)
  @js.native
  class Child extends Parent

  def main(args: Array[String]): Unit = 
    println(new Child)
}

```

On 1.0 `asddsaasd` (`rsocket-websocket-client/RSocketWebSocketClient` in this example) is included among the modules webpack will look for, while it (I would say rightly) isn't for 0.6. This is actually quite bad, this pattern is used throughout the generated code, and I don't see an easy replacement.

**Comment by oyvindberg** [comment]
Any chance you could look at this difference in behavior between Scala.js 0.6 and 1, @sjrd? 

I guess it's a bug, but I'm not sure if this would be related to Scala.js itself or scalajs-bundler.

**Comment by sjrd** [comment]
I'm not sure yet whether to consider that a bug or a missed opportunity for optimization. But feel free to open an issue in the Scala.js repo, or I'll forget about this. Thank you.

**Comment by mushtaq** [comment]
@oyvindberg should I open an issue in the Scala.js repo with your minimal example?

BTW, This is the only thing preventing our migration to Scala.js 1.x

**Comment by oyvindberg** [comment]
I want to dig a big further to see if there is anything I can do on my side. In this particular case  `'rsocket-websocket-client/RSocketWebSocketClient'` actually exists as  `'rsocket-websocket-client/build/RSocketWebSocketClient'`, and we can choose that module name instead.

In Typescript the two names are the same because of a shortcut in module name resolution. Indeed you can import both module names mentioned above in a Typescript file, and the shortest one will fail there too at runtime. I guess the reason is that node doesn't support the same short module names.

If I determine we cannot fix this in the converter I'll open an issue in the Scala.js repo.

As a workaround you can copy/paste the class you use along with its parent into your codebase and just change that one import or make the parent into a trait.

**Comment by mushtaq** [comment]
Thanks for looking into it. I will also explore your suggestion.

**Comment by oyvindberg** [comment]
Nevermind, there is no way to infer that `build` folder from any of the files in the `@types/rsocket-websocket-client` package, and hence no way the converter can get this right.

I'll create the issue tonight.

**Comment by oyvindberg** [comment]
Also breaks [this typescript pattern](https://github.com/vega/vega/blob/master/packages/vega/index.d.ts)

**Comment by oyvindberg** [comment]
This is finally fixed now with Scala.js 1.1.0 and ScalablyTyped 1.0.0-beta13 which I just released :)

**Comment by mushtaq** [comment]
Thank you!
