### ISSUE TITLE
directions on creating a new flavour

### ISSUE THREAD

**Issue by aappddeevv** [ScalablyTyped/Converter#136]
I would like to add a flavor for scalajs-reaction. Are there some starter guides for that? scalajs-reaction uses plain scala.js and a function component/hooks-first approach so the outputs are fairly simple.

**Comment by oyvindberg** [comment]
Hi there, thanks for you interest in writing a flavour :)

I'll try to do a longer writeup within a few days because I know this bit of code is not as clear as it should be.

In the meantime here are some pointers:

The overall structure of what a flavour currently does can be seen [here](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/FlavourImpl.scala#L91-L117). It's a function from `PackageTree` to `PackageTree`, so it's very powerful in that it can rewrite the code in any way you can come up with. 

Currently the flavours typically:
- generate companion objects for "simple" traits
- rewrite a bunch of types from the typescript types to corresponding types in scala-js-dom or the given react wrapper library
- try to identify all react components and group them by name
- generate code for each react component which makes them easy to use

The meat is in the code generation parts, see the [scalajs-react flavour](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/GenJapgollyComponents.scala) or the [slinky flavour](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/GenSlinkyComponents.scala)

I recommend you look at the scalajs-react flavour. The slinky one has some added complexity because it's used both for native and web, and because we remove DOM props.

To start off, you can take an example component like [this one](https://github.com/ScalablyTyped/Converter/blob/master/tests/react-integration-test/check-japgolly/s/semantic-ui-react/src/main/scala/typingsJapgolly/semanticUiReact/components/Accordion.scala) and manually rewrite it to what you want your flavour to generate. I can guide you from there

**Comment by aappddeevv** [comment]
Roughly...
```scala
// imports...
object Accordion {
 @jsenrich trait Props extends js.Object {
    var activeIndex: js.UndefOr[Double | js.Array[Double]] = js.undefined
    var as: js.UndefOr[js.Any] = js.undefined
    var className: js.UndefOr[String] = js.undefined
    var defaultActiveIndex: js.UndefOr[Double | js.Array[Double]] = js.undefined
    var exclusive: js.UndefOr[Boolean] = js.undefined
    var fluid: js.UndefOr[Boolean] = js.undefined
    var inverted: js.UndefOr[Boolean] = js.undefined
    var onTitleClick: js.UndefOr[js.Function2[ReactMouseEvent[dom.html.Div], Props], Unit]] = js.undefined
    var panels: js.UndefOr[SemanticShorthandCollection[Props]] = js.undefined
    var styled: js.UndefOr[Boolean] = js.undefined
    var key: js.UndefOr[String|Int] = js.undefined

  // If we generate some cool apply and immutabl'ish functions here to enrich Props
  // we can remove the macro annotation above.

  @JSImport("semantic-ui-react/dist/commonjs/modules/Accordion", JSImport.Default)
  @js.native
  object JS extends ReactJSComponent

  def apply(props: Props) = createElement(JS, props)
}
```

**Comment by oyvindberg** [comment]
Ok, cool! 

Just out of curiosity, why traits instead of `apply` methods with default parameters?

First observation is that we already have `@ScalaJSDefined` traits for a lot cases, and there are rewrites to scala-js-dom types which can be reused. Most of this should be easy.

That said, there is a macro there, I would strongly prefer if we can generate the results of the macro directly.
I know from the work on Slinky (where projects typically has it enabled) that just having the compiler plugin enabled triggers a bunch of errors on otherwise good code. I have one bug fix [commited](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/transforms/AvoidMacroParadiseBug.scala), but there are more, and nobody is fixing them. 

what is the result of the macro? immutable setters? 

I would be interested in exploring how to extend the [code which generates companion objects](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/GenCompanions.scala) also generate some sugar on top like immutable setters.

**Comment by aappddeevv** [comment]
I'm fine generating the results of the macro directly. It has an apply method (as you indicate) plus the additional immutabl'sh setters such has `withKey` or `withOnTitleClick`. Much asked the @data macro that's out there for normal scala. It also has a duplicate and combine method. The problem is that for large UI toolkits, you often merge objects together from 2-3 different places so just an apply method does not get you very far. 

scalajs-reaction use a very simple model, it does not macros at all nor classes, inheritance or much of anything actually. Just normal scalajs js functions and traits.

I believe the trait is the right pattern with vars/vals because it helps you enforce require attributes. I also have some more advanced patterns around js object manipulation that I think are best practices that I would like to have generated regarding required vs optional arguments.

**Comment by oyvindberg** [comment]
Ok, let's have a look at what's possible

Let's take an example simple trait which receives a companion object with an apply method:
```scala
trait RowProps extends js.Object {
  var align: js.UndefOr[top | middle | bottom | stretch] = js.undefined
  var gutter: js.UndefOr[Gutter |(js.Tuple2[Gutter, Gutter])] = js.undefined
  var justify: js.UndefOr[start | end | center | `space-around` | `space-between`] = js.undefined
  var prefixCls: js.UndefOr[String] = js.undefined
  var `type`: js.UndefOr[flex] = js.undefined
}

// I'll refer to this below
type Gutter = scala.Double | typings.antd.PartialRecordBreakpointnu

object RowProps {
  @scala.inline
  def apply(
      align: top | middle | bottom | stretch = null,
      gutter: Gutter |(js.Tuple2[Gutter, Gutter]) = null,
      justify: start | end | center | `space-around` | `space-between` = null,
      prefixCls: String = null,
      `type`: flex = null
  ): RowProps = {
    val __obj = js.Dynamic.literal()
    if (align != null) __obj.updateDynamic("align")(align.asInstanceOf[js.Any])
    if (gutter != null) __obj.updateDynamic("gutter")(gutter.asInstanceOf[js.Any])
    if (justify != null) __obj.updateDynamic("justify")(justify.asInstanceOf[js.Any])
    if (prefixCls != null) __obj.updateDynamic("prefixCls")(prefixCls.asInstanceOf[js.Any])
    if (`type` != null) __obj.updateDynamic("type")(`type`.asInstanceOf[js.Any])
    __obj.asInstanceOf[RowProps]
  }
}
```

Adding some sugar to this is easy:
```scala
trait RowProps extends js.Object {
  // ...
}

object RowProps {
  @inline final implicit class Ops(private val x: RowProps) {
    @inline def combine[T <: js.Object](v: T): RowProps with T =
      js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, v).asInstanceOf[RowProps with T]
    @inline def withGutter(v: js.UndefOr[Gutter |(js.Tuple2[Gutter, Gutter])]): RowProps =
      js.Dynamic.global.Object.assign(js.Dynamic.literal(gutter = v.asInstanceOf[js.Any]), x).asInstanceOf[RowProps]
    // ...
  }

  @scala.inline
  def apply = ???
}
```

And this is where it gets interesting and there is some real design space to work with.
In general we can't do interesting things with the types in a Javascript trait, they all need to describe the Javascript world. Scala developers likely will favour `Option` over `js.UndefOr`, but they are not the same.

However, if we introduce implicitly added members on top, we're free to! We already exploit this in the `apply` methods for the generated companion objects, for instance they use scala functions instead of `js.FunctionN`, and they use `null` instead of `js.UndefOr` for better type inference.

So what can we do here? I picked the `gutter` prop because it shows a few possibilities. We can explode the union type into overloaded methods, or even better non-overloaded methods if we can come up with a naming standard.

```scala
  @inline implicit class Ops2(private val x: RowProps) {
    @inline def withGutterUndefined: RowProps =
      js.Dynamic.global.Object.assign(js.Dynamic.literal(gutter = js.undefined), x).asInstanceOf[RowProps]

    @inline def withGutterGutter(v: Gutter): RowProps =
      js.Dynamic.global.Object.assign(js.Dynamic.literal(gutter = v.asInstanceOf[js.Any]), x).asInstanceOf[RowProps]

    @inline def withGutterTuple2(v: (Gutter, Gutter)): RowProps =
      js.Dynamic.global.Object
        .assign(js.Dynamic.literal(gutter = js.Tuple2.fromScalaTuple2(v)), x)
        .asInstanceOf[RowProps]
  }
```

I think the use site shows the difference clearly
```scala
new RowProps { align = top }.withGutter(js.defined(js.Tuple2(2.0: Gutter, 2.0: Gutter)))
new RowProps { align = top }.withGutterTuple2((2.0, 2.0))
new RowProps { align = top }.withGutterUndefined
new RowProps { align = top }.withGutter(2.0)
```

There will be some more complications probably, but the first part of this is trivially implementable :)

And just to have that said I too favoured `@ScalaJSDefined` traits for representing complex props, but I met nothing but pushback on that, heh

**Comment by aappddeevv** [comment]
If I recall, you can just skip all the nulls on the apply. Anything required should be whatever type it is, anything optional, should be js.UndefOr with a default of js.undefined. You can remove all the `if (x == null)` type checks and directly cast the value, whatever it is, to js.Any and stick it in the js.Dynamic.literal directly. I think they UndefOr's go in as undefined so they do not get defined on the object anyway.

```scala
def apply(x: js.UndefOr[String], y=...) = js.Dynamic.literal("x" -> x.asInstanceOf[js.Any], "y" -> ...)
```

Maybe its faster with the null test and `updateDynamic` but don't know.

The `withX` methods just need to take whatever the parameter is, `js.Undef[String]` or `String` depending on whether its optional. You could drop the `withGutterUndefined` although I had not thought of that and kind of like it (I may add that to my macro :-)).

The other nice thing about properly defined scala.js traits for the props is you can further target them for macros or implicit and at least the val/vars are robust...in other words, you can more easily enable further customizations since codegen is never perfect.

I think I define, have to check, combine both with the Props type directly as well as `def unsafeCombine[P <: js.Object](props: P|js.Dynamic)`.

But you have the idea right.

**Comment by aappddeevv** [comment]
The other issue I am playing around with is very controversial which is to split props into a PropsBase, PropsInit and Props. That way you can control requirement parameters and non-requirement parameters more easily using standard trait instantiation versus `apply` and `with*` methods. But that's a lot more work.

**Comment by oyvindberg** [comment]
So I implemented a basic version in #137 . Note that the changes don't affect the generated react components, only the companion objects for normal traits. It has some imperfections regarding props with union types (including undefined).

My first comment is that it's a lot of code. We can possibly make it a bit less by leaning of the generated sugar for parent classes.

A decent example is [AccordionProps](https://github.com/ScalablyTyped/Converter/blob/sugar/tests/react-integration-test/check/s/semantic-ui-react/src/main/scala/typings/semanticUiReact/accordionAccordionMod/AccordionProps.scala)

**Comment by aappddeevv** [comment]
That looks about right. I think that the implicit class needs to use `implicit class Sugar(private val x: ...) extends AnyVal { ... }` to avoid the allocation.

I think the other thing is that people may not like `combine` name because they target application addition using other libs. I think I named it `combineWith`.

**Comment by oyvindberg** [comment]
I'm by the way somewhat working towards this. Currently trying to refactor the flavours into an easier to describe state, and enabling use cases like this

**Comment by aappddeevv** [comment]
Cool...I'd like to get my flavor going. Like I said, you can build that has no (as near as I can tell) dependencies on a toolkit much like typescript compilation for JSX, you can make it totally generic output.

**Comment by oyvindberg** [comment]
Current status can be seen in https://github.com/ScalablyTyped/Converter/pull/138/commits/65ab888ade8bc6b3f0c6882d858235463c6fe7e2 . I enabled ~~sugar~~ implicit ops for one of my test cases which generates scalajs-react integration code for a bunch of react code, chosen because it has some interesting feature interactions with this.

I had to resort to a pattern of `Self` types as you'll see. The point is for a given class to inherit all the implicit ops added to its super classes so we dont have to duplicate them.
The only real issue outstand is to decide which/how many overloads to generate for a given prop with a union type.

With this encoding we do add a bunch of code. Compiling the esnext stdlib took about 30 seconds longer with all this, which isnt too bad

**Comment by aappddeevv** [comment]
It probably needs to be an option then.

**Comment by oyvindberg** [comment]
You should have a look at [1.0.0-beta13](https://github.com/ScalablyTyped/Converter/releases/tag/v1.0.0-beta13)  which I just released @aappddeevv 

I took a (mutable) variant of what we discussed above and used it for the Slinky flavour, and will adopt it for all other generated companions as well (it's currently hidden behind a configuration options which will be the default soon). I think it is turning out really really well. Hope you can have a look and see if what's here already is good enough for you.

If you still want a flavour to do it differently I think all the flavour-related code is in a *much* better state now, so I would be happy to guide.

For now I'll close the issue, but feel free to comment further, or drop by gitter or whatever :)

**Comment by aappddeevv** [comment]
I'll do that. After review, it looked daunting for me to create a flavour even if the output for scalajs-reaction is fairly simple and direct.

**Comment by oyvindberg** [comment]
Yeah, I'm not gonna claim it's the easiest code around, but I think you could get far with little.

If the flavour enables `stExperimentalEnableImplicitOps`, all the `Props` types will already have builders. Then it's just a matter of collecting all components in one place, and perhaps a few type aliases. It would be pretty much like what I just deleted [here](https://github.com/ScalablyTyped/Converter/commit/659ef427f767430198a967819ef2f2f8593d5e42#diff-c122c135bc572a87ae4281839c7d0479). That, plus perhaps a few [type conversions](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/SlinkyTypeConversions.scala).
