### ISSUE TITLE
Support local typescript project

### ISSUE THREAD

**Issue by aappddeevv** [ScalablyTyped/Converter#142]
This is a request for a paragraph or two on how to run the converter on an in-place typescript code base part of an integrated project. It is not present on npm but may have npm dependencies.

The scenario is that a mixed code base of typescript and scala.js needs conversion of one's own typescript files (and any dependencies on them which would come from npm). So imagine that I have a directory of typescript files and I have another directory of scala files. Those scala files need to use artifacts from the typescript directory. That typescript directory is a standard typescript project with a package.json, tsconfig.json and src folder, etc.

**Comment by oyvindberg** [comment]
So this is not going to work 100% OOTB, but it should be easy to get there. First two constrains:

- You'll need to build the typescript project so you have a folder with `.d.ts` files, because the converter cannot read full typescript files. 
- It'll help your dev flow a lot if the typescript code can be versioned somehow, since the plugin checks for changes on each compile and performs a (pretty slow, but one time) conversion/compilation when the answer is yes.

If that situation is workable for you we can add an escape hatch to do this.

Another thing you might look at (very soon, or now if you compile the converter yourself) is to run the converter as and CLI utility, I just added #143

**Comment by aappddeevv** [comment]
A CLI would be fine and if that's easiest I'm all for that.

**Comment by oyvindberg** [comment]
Not sure exactly what you mean. The converter sbt plugin has a "run" command, which is `tsImport`, but you'll find the interface of exported sbt settings too constrained to do what you want right now. Likewise the `cli` module will be runnable with a `main` through coursier once I publish it. 

By the way what is the workflow you're imagining with this?

**Comment by aappddeevv** [comment]
Mixed codebase projects that are not published to npm. If you create an app server in node.js, for example, parts of it are probably written in typescript. However, other parts can be written in scala.js. But, the scala.js needs to import various interfaces from the typescript part of your server. This allows a single project to gradually adopt scala.js or use those parts of scala for processing that scala may be better for.

**Comment by oyvindberg** [comment]
Ok, thanks for the explanation.

So the use case could actually be rather important for adoption of Scala.js, so I'm motivated to give it a shot.

Let's get straight to the problem as I see it: The conversion process and (especially) the compilation is slow. Too slow to fit well in between a rapidly changing Typescript codebase and a Scala.js codebase which depends on it. 

I think the current design with an sbt plugin which caches entire runs is starting to become a very good compromise. You build on a new machine? It'll take two minutes extra to build the first time. You bump a version of a typescript dependency? again it takes two minutes. Otherwise usage is super fast.

With the new CLI tool you can publish builds to your own Bintray account (or elsewhere if somebody contributes code) an organization can build typing libraries centrally and otherwise pay no cost at all at build time.

What we're talking about here is a bit different, because I suppose the typescript code changes often - otherwise it would be trivial for you to publish it to an internal npm repository.

The question then is *when* do we update to reflect such a moving target? I suppose when the API changes, but it's hard to tell when that happens without running the entire conversion pipeline. It can of course be manual with the CLI tool, or the plugin could diff the built typescript code for (meaningful) changes and then run a new conversion when needed.

I can hack up a way to use the plugin with a non-npm project rather quickly, but deciding on the *when* mentioned above will be the hard part. If you have any thoughts I'd be happy to hear them

**Comment by aappddeevv** [comment]
I'm thinking the conversion process only needs to run when the immediate codebase changes and exclude regeneration of anything in package.json.

I'm not sure how the converter runs today but here are some thoughts. I'm assuming that a conversion run on a single .d.ts is pretty fast and unobtrusive.

* The converter should be able to run on a single .d.ts file and output a single .scala file. If a collection of .d.ts files change, then it runs on that collection. You may have to denounce file changes to detect that.
* Rerun only on an individual .d.ts file only when that .d.ts file changes.
* Rerun if package.json dependencies change and only on those packages that change e.g. a version number change or something is added/removed. This happens infrequently over time as your dependencies stabilize.

**Comment by oyvindberg** [comment]
I'll rename the issue to reflect my current understanding of what we want to accomplish here. I'll call this use case realtime conversion for now.

Your assumption doesn't really hold, let me go into some details here with some semi-solutions of how to approach it.

## Conversion time
The converter converts entire libraries at once, and that's unlikely to change. At best all the downstream dependencies of a given file could be reconverted (like zinc does for scala files), but that requires a lot of machinery we don't currently have. 

Where you are right though, is that conversion of a whole library typically is typically fast (from tens of milliseconds to tens of seconds,depending on the size and complexity of the typescript library, and how much the JVM has optimized the conversion code).

A conversion of a single library requires that we have complete trees for all its upstream dependencies available. In particular we always need the stdlib, which amount to 20 seconds plus, depending on conversion parameters.

I think some more clever caches can alleviate this by serializing the dependency trees once we have generated them the first time.
In fact, if you want to contribute time towards this goal I think finding a blazing fast way to (de-)serialize the [Typescript](https://github.com/ScalablyTyped/Converter/blob/master/ts/src/main/scala/org/scalablytyped/converter/internal/ts/trees.scala) and [Scala.js](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/tree.scala) compiler trees would be a very good place to start.

## Compilation time
When we detect that we have a scala tree representation of a typescript library which we don't have compiled artifacts for, we compile it. Compilation time is longer than conversion time, and generally out of our control. This means that as things stands now, you would pay for a full, non-incremental compile for the real-time library as well for any change.

An earlier iteration of the sbt plugin worked as an sbt resource generator. If we use that approach for realtime conversions, we can let zinc and sbt do their magic to only recompile what's necessary.

With both these changes together I'm pretty confident we can get incremental conversions down to a few seconds.

**Comment by aappddeevv** [comment]
Keeping all the trees in memory might really increase memory usage and the JVM is not always good about giving back memory (perhaps the new gc works better), but I'm thinking that if it dramatically increases memory, we probably should go with a CLI that can be run under the manual control of the programmer.

**Comment by oyvindberg** [comment]
Memory is not really an issue, it wont be many megabytes. The CI job keeps 8500 * 3 trees in memory at once on an 8 GB heap IIRC, and still finds the memory to run scalac on hundreds of thousands of lines. 

The serialization i talked about above would be needed exactly because we don't want to keep it in memory, but it should be persisted across sbt restarts.

**Comment by oyvindberg** [comment]
Ok, so nevermind all the speeding up things. I pushed a small commit which solves your problem last night @aappddeevv , see the one linked just above.

It was pretty cool, I tried it on a typescript project I worked on last year and everything seemed to work! :) 

If you want to try it you can clone the repo, publishLocal and run it like in the docs, just replace the `-r` argument to coursier with `-r ivy2local`.

**Comment by aappddeevv** [comment]
I'll give it a try!

**Comment by aappddeevv** [comment]
Ran into an error. Which is below...

How does the CLI know where the .d.ts files are? I output them to a "declarations" folder at the top-level or does it just scan the topdir downward looking for them?

```sh
arn ] 2020-04-13T17:04:51.396663Z Phase3Compile.scala:230  Building /home/glampshire/.ivy2/local/org.scalablytyped/logform_sjs1_2.13/2.1.2-ad4089/jars/logform_sjs1_2.13.jar... [id => logform, thread => 1, phase => build, flavour => Normal]
[error] 2020-04-13T17:04:51.815693Z Phase3Compile.scala:250 err Compiling logform (16 Scala sources)
[E] [E1] src/main/scala/foo/logform/mod/format.scala:16:24
[E]      not found: type Format_*
[E]      L16:   def combine(formats: Format_*): Format_ = js.native
[E]                                  ^
[E] src/main/scala/foo/logform/mod/format.scala: L16 [E1]
Compiled logform (378ms)
[E] Failed to compile 'logform'
```

**Comment by oyvindberg** [comment]
>  Is there a way to publish the jars to a local "lib" dir?

Not so far, but if you give it a recognizable org name it's easy to clean them out manually. Feel free to PR a change for that, it should be easy

> Ran into an error

logform is a known library which cannot be converted yet, add `--ignoredLibs=logform` to get around it.

> How does the CLI know where the .d.ts files are? I output them to a "declarations" folder at the top-level or does it just scan the topdir downward looking for them?

It scans for them, though you could guide it with a `typings` or `types` entry in `package.json`. 

My assumption was that Typescript builds `.js` files and `.d.ts` files in the same directory, say `dist`. We then generate imports such as `frontend/dist/myfile`, which hopefully you can get webpack to resolve.

If you'd like to change anything about that I'm definitely open to suggestions

**Comment by oyvindberg** [comment]
did you have the chance to try it again @aappddeevv ? I'm pretty excited about what this feature can enable :)

**Comment by aappddeevv** [comment]
Yes, it did generated with just that one exclusion. We probably need a switch that says keep on translating even if there is an error especially if it is not a lib that is used directly. I'm reviewing the conversions to see how it translated the types.

**Comment by aappddeevv** [comment]
It looks like the typings converted quite well for the local project. I'll use them and see how smooth it is. I know this is quite complex so its a tremendous effort to make this work.

A few thoughts:

* Can we specify the location of the local project typing vs assuming it is in the same as the sbt project?
* Output names: I've been using snake case for my typing because it more javascript and easier to remember. A switch that uses snake case would be good. `foo-bar` js becomes `foo_bar` and `@blah/foo-bar` becomes a hierarchy with blah, then foo_bar. Or at least something like that.
* enums: I think I saw that enum values get push into a large enum object. There may be good reason for that, however, I've found that the sjrd recommended pattern of express enums to be quite good e.g. `@js.native abstract MyEnum extends js.Any` then `object MyEnum { val blah = 0.asInstanceOf[MyEnum]; ... }`. That way you write `MyEnum.blah` as the value.
* It looks like it did not catch functions declared with keyOf arguments. For example, if a declaration has `somefunc(x: keyof Blah)` it looks like it stuck "string" as the arg vs `Blah`.

**Comment by aappddeevv** [comment]
I also thought it was fast enough.

**Comment by aappddeevv** [comment]
I know this sounds crazy but it would also be nice to have an option that dumps all the sources to a dir for inspection. I dumped them from the jars and ideally the IDE is super good, but that's not always the case. If there was an output `--scala-output-topdir` and `--scala-output-docs-topdir` option that would be great. The docs option is probably more important. Maybe the docs can be programmed to include the sources.

**Comment by aappddeevv** [comment]
Thank you for helping with this.

**Comment by oyvindberg** [comment]
Thanks for the feedback! I'll comment on a bit of it now, and the rest tomorrow.

> Yes, it did generated with just that one exclusion. We probably need a switch that says keep on translating even if there is an error especially if it is not a lib that is used directly. I'm reviewing the conversions to see how it translated the types.

It already does, but doesn't present it that way. Note that any library depending on that failed library is impossible to compile.

> I forgot to mention that I think it translates your own "ts" code better because your own ts code is usually much more type friendly, e.g., no heavy overloading the same method with multiple input types. The luxon dates library is a good example of an API that separates the types out cleanly and its translation is pretty good.

Indeed! It's not hard to see if some code is written in Javascript and typed after the fact, or if it is a native Typescript project!

> Can we specify the location of the local project typing vs assuming it is in the same as the sbt project?

Can you clarify this? Which location do you want to change? What appears in the generated typings? or where it comes from?

> Output names: I've been using snake case for my typing because it more javascript and easier to remember. A switch that uses snake case would be good. foo-bar js becomes foo_bar and @blah/foo-bar becomes a hierarchy with blah, then foo_bar. Or at least something like that.

I'm a bit meh on this. It would double the testing surface, and snake_case is highly unusual in Scala code.

**Comment by aappddeevv** [comment]
I don't generate typings for my project, nodejs app server, since they are not used when running, its not a library, and its not shared. I generate the typing only for conversion and I generate them into a specific directory. I do have a few misc .d.ts files around so scanning the entire project directory downward picked up a few undesired things...not much. But if its inproject, perhaps the arg is either "true" and its does scanning or its a path to the typing that are considered "inproject." Low priority.

I understand about snake_case. But it does help emphasize that its "js" sourced. For a graphql-to-scala code generator that I open sourced, you can define a convert name convention to handle this in one location in the code. Or you could make it "service" thing in the jvm world (or don't do service if this can be compiled to js which would open up other possibilities).

**Comment by aappddeevv** [comment]
BTW, other than the feedback dialogue, I feel this issue can be closed since its working.

**Comment by oyvindberg** [comment]
I finally had some time to go through the rest:

> enums: I think I saw that enum values get pushed into a large "object of strings." There may be good reason for that, however, I've found that the sjrd recommended pattern of expressing enums to very helpful e.g. @js.native abstract MyEnum extends js.Any then object MyEnum { val blah = 0.asInstanceOf[MyEnum]; ... }. That way you write MyEnum.blah as the value.

This is already done for many cases. Note that there are actually three different things referred to as enums in typescript (`enum`, `const enum`, union of literals), as well as the complication that an enum might be defined in a module but not exported from it (under the same name), and there are some differences in how they are encoded in ScalablyTyped.

The "object of strings" you saw, for instance [stdStrings.scala](https://github.com/ScalablyTyped/Distribution/blob/master/s/std/src/main/scala/typings/std/stdStrings.scala), is actually a collection of all string literals in the library. Some of them will form part of a `const enum` or a named union of literals enum, for instance `2d` which is part of [OffscreenRenderingContextId](https://github.com/ScalablyTyped/Distribution/blob/master/s/std/src/main/scala/typings/std/OffscreenRenderingContextId.scala).

OTOH full blown enums are actually javascript values, so we output a facade for them, see for instance [InvalidatedProjectKind](https://github.com/ScalablyTyped/Distribution/blob/master/t/typescript/src/main/scala/typings/typescript/mod/InvalidatedProjectKind.scala)

I think all this is in a pretty good shape, but if you had a particular example where `MyEnum.blah`  is not available that should probably be fixed.

> It looks like it did not catch functions declared with keyOf arguments. For example, if a declaration has somefunc(x: keyof Blah) it looks like it stuck "string" as the arg vs Blah. The luxon lib type DateTime.get showed this behavior.

Good catch, this was easy to fix. I'll push a commit soon

> I ran the command twice with different org parameters and it looks like it outputs to a different jar name--appending some type of hash. Is that configurable, I would just rather output to the same jar and overwrite what's there. I can see why you would want a hash sometimes, however, its hard to build a pipeline if you don't know a stable name ahead of time.

The hash is crucial for avoiding recompiles, for keeping things working if you compile the same libraries with different parameters or different versions of dependencies and whatnot. 

I think you'll do better with either 1) a manual approach where you build/publish typings and then consume them with a given version number (easiest), or 2) fully automate everything, in which case the cli tool can easy produce something machine readable.

 > If I leave off the org, I get typing placed into that by default. If I have a local project we are probably ok with just the project name being the top-level package.

Yeah, it needs to be that way to avoid name collisions.

> I know this sounds crazy but it would also be nice to have an option that dumps all the sources to a dir for inspection. I dumped them from the jars and ideally the IDE is super good, but that's not always the case. If there was an output --scala-output-sources-topdir and --scala-output-docs-topdir option that would be great. The docs option is probably more important. Maybe the docs can be programmed to include the sources.

They already are actually. If you look in the directory with package.json there will be an out folder with all the sources. A cool thing is that since all the libraries are published locally you can open the projects inside there in intellij or metals and get everything resolved.

That said, you should attach the jars to your project through sbt and have them show up in your IDE.

What do you want the docs option to do by the way? If you're talking about scaladoc I don't believe it's the right choice in this context. The reason is simply that the source is the documentation already, so there is nothing to be gained from generating anything based on that.

> I also thought it was fast enough.

Happy to hear it! :)

**Comment by oyvindberg** [comment]
I'll keep the task open a bit longer to see what more we come up with which should be fixed

**Comment by aappddeevv** [comment]
The doc issue is that its easy to search and browse scaladocs. Some of my libs are enough that I've taken to using my own generated scaladoc to find things these days. I see that "out" folder (added to .gitignore now).

I don't think we all have nice IDEs so I can't count on the IDE being helpful for docs and such.

**Comment by oyvindberg** [comment]
By the way I wrote this comment more than once, but it comes across sounding harsh. Please interpret in the best meaning, I'm genuinely curious.

I don't get this. Why would you use scaladoc to navigate code, and own at that? what benefits does it have over an IDE?

There might be some hypothetical scala users out there not using an IDE. I know in the past some people did repl-based development but that doesn't work for Scala.js. If somebody uses neither I don't know what to say to that.

**Comment by aappddeevv** [comment]
I either use emacs or vscode, both of which have weaker support for navigating code and documentation--sometimes non-existent. It's always good to have the code, but it's often easier and faster to read the scaladocs if just want to know the type signature and then browse around to understand how it all connects. Personally, I like it when the scaladocs have links to the code. After I understand how a particular code base was generated, just reading the docs when I need something is much easier. With the assumption that not all "people who generate" will push to maven and javadocs.io picks it up automatically, I just wanted to get the docs output as an option. I do this for my own code base of facades, I always generate docs and use those.

For ts/js libs, it is an entirely different issue though because the docs are often insufficient or so poorly formatted that browsing is painful and source code is the best way to validate the API :-). This is also why I am concerned that the new dotty doc format is more difficult to browse easily but that's another issue.

**Comment by aappddeevv** [comment]
I'm also wondering about the top-level package thing as well...none of these are showstoppers but it's not clear that you would have name collisions in the output jars and you can fully reference types in your generated code. If you have name collisions between libraries, that's resolvable by the programmer quite easily. I ran into the same issue with a code generator I wrote but then just used fully qualified names and it solved it.

**Comment by oyvindberg** [comment]
Right. It strikes me as an astonishingly inefficient workflow, but to each their own :D 

If you want to invest time into generating the docs with a flag I'll accept a PR and guide you as needed, but I wont work on that myself.


About top level names, rember that scala is a very flexible language. The converter uses fully qualified paths for everything internally, and only shortens names when possible as part of the printing to files before compilation. Now we have exactly five javascript identifiers which might break compilation with name collisions (`typings` (or whatever you set as `outputPackage`), `js`, `scala`, `org`, `com`). I'll find a solution for those some day, but havent gotten around to it. If we don't hide all the fully qualified names behind a known name *any* identifier can conflict with pretty much anything else. It's absolutely crucial.

**Comment by aappddeevv** [comment]
What’s inefficient about reading the documentation?

**Comment by aappddeevv** [comment]
But I think it the sources are there in “out” it should be a simple trick
to generate docs from them so that can be handled out of the tool. So that
issue is solved.

**Comment by oyvindberg** [comment]
The looking up, searching, finding and reading part, as opposed to just asking the IDE. Anyways nevermind, I'm sure you have your reasons :)

Generating docs from those sources can actually be super easy since you mention it, you can use sbt to build/publish them. All the typing libraries come with build files.


But ok, I really appreciate the discussion, loads of useful comments! I'll try to wrap up a few loose ends from the discussion:

- snake_case. I'm gonna say no for now. The main reason is that I want to write usage documentation, and there are the demo repositories. The code there should be as copy/pasteable as possible.

- enums: If you had a particular example where `MyEnum.blah` is not available that should probably be fixed. Please file another issue if you do

- local typescript projects
The feature itself works kind of. I'm really not sure if it's "enough" yet, but I can slap an "experimental" note on it. I really think that this can become a game changer for people using typescript who want to try Scala.js!
If you come up with anything please let me know.

**Comment by aappddeevv** [comment]
Ah, got it about the IDE.  I probably would not make the assumption that
everyone uses IDEs that are as capable as that.

Thanks for your help.
