### ISSUE TITLE
useScalaJsDomTypes (and type conversion in general) is ignored in some situations

### ISSUE THREAD

**Issue by smarter** [ScalablyTyped/Converter#146]
Apparently, overloading can prevent type conversion:
https://github.com/ScalablyTyped/Converter/blob/ac593fadc18468b45c2adc074dd6e3fc2124eb5a/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/CastConversion.scala#L73

It would be nice if this was documented. It would also be interesting to know if this behavior can be improved. In which situations can a clash occur? I I look at https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/ScalaJsDomNames.scala, the mapping seems to be one-to-one, so no clashes can possibly occur right? Instead of checking if the input types of two overloads are different, could this be changed to check if the input types are different __and__ the output types are the same? That should prevent false positives.

**Comment by oyvindberg** [comment]
Hey there @smarter and thanks for your interest :)

### Background
This type rewriting phase, `TypeRewriterCast`, runs after the converter has already computed an otherwise final version of the trees, which can then be printed and given to `scalac`. The reason it is that way is because we're translating into types we don't have the definition for, so afterwards the trees are broken in a sense.

### So where this did break compilation? 

React components have many names, and we collapse them into [one](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/SlinkyTypeConversions.scala#L35) for the slinky and scalajs-react flavours, as the distinction is very rarely useful. This broke everything :)


### Can it be improved?

The best way to fix this problem would be to read probably the class file pickles and translate into the trees used here. In that case we could have a perfect type rewriting phase, including for inheritance which is not currently supported at all.

This sounded like more time than I had, hence this heuristics. 

#### Can the heuristics be improved? 

It is coded defensively now, with the assumption that we cannot compare type names we don't have the definition for, since they may be type aliases referring to each other. If we say it's the responsibility of the caller of `TypeRewriterCast` of to not map types to such type aliases, then yes, we can do what you propose :)

I'll give it a shot within some days.


Also note that if you ran into this with a released version of the plugin, I [improved](https://github.com/ScalablyTyped/Converter/commit/2ed758b9df954b79da1dbf39ca218600570299c9) this slightly a few days ago, so it's possible your concrete problem is fixed already.

**Comment by smarter** [comment]
> React components have many names, and we collapse them into one for the slinky and scalajs-react flavours, as the distinction is very rarely useful. This broke everything :)

I see, so you ended up with multiple overloads with the exact same type arguments? In that case, could you run something like `.unique` to drop the duplicates?

> I'll give it a shot within some days.

Cool, thanks!

> Also note that if you ran into this with a released version of the plugin, I improved this slightly a few days ago, so it's possible your concrete problem is fixed already.

Yes I noticed this! It's better but in [webgl2](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webgl2/index.d.ts) for example, there's some overloaded methods like `texImage2D` which are still problematic.

**Comment by oyvindberg** [comment]
> I see, so you ended up with multiple overloads with the exact same type arguments? In that case, could you run something like .unique to drop the duplicates?

Not necessarily exact. As I'm sure you can imagine, there might be type aliases and differently named type parameters and such. 

I gave it a shot now in #148 . I'm trying to determine a clash by looking for overloaded methods with same number of params, and with different type name for parameter at same index before translation and same type name after. It's probably not failsafe, but I'll kick off a CI build and see if there is any breakage in practice.

Also notice that `webgl2` was AFAIU standardized, so such you'll find it in `std` already (as long as you havent trimmed [stStdLib](https://scalablytyped.org/docs/plugin#ststdlib) to exclude the DOM APIs)

You can access it like this:
```
  val x: typings.std.HTMLCanvasElement = ???
  val ctx: WebGL2RenderingContext | Null = 
    x.getContext_webgl2(typings.std.stdStrings.webgl2)
```

If you're using newer APIs like this, you may find that `std` is more comprehensive than scalajs-dom

**Comment by oyvindberg** [comment]
I released the changes in beta11. Note that I didn't have time to look very thoroughly at the results, so please report back if you still see issues :)

**Comment by smarter** [comment]
Thanks a lot! The changes do help!

> Also notice that webgl2 was AFAIU standardized, so such you'll find it in std already (as long as you havent trimmed stStdLib to exclude the DOM APIs)

I tried that and noticed that calling `texImage2D` again required cast because in the std bindings it's defined as:
```typescript
texImage2D(..., source: TexImageSource)
type TexImageSource = ImageBitmap | ImageData | ...
```
whereas in the webgl2 bindings it was defined as:
```typescript
texImage2D(..., source: ImageBitmap | ImageData | ...)
```
it's a bit surprising that using a type alias changes the encoding. The fake union types of scala.js aren't perfect but they do work in some situation (and hopefully can e replaced by real union types with dotty), so maybe it's worth having a config option in the plugin to decide if unions should be used or not by the converter?

**Comment by oyvindberg** [comment]
Aha, I get the issue. Without `useScalaJsDomTypes` this makes a lot of sense. 

Union types enables grouping of types in an ad hoc manner
```typescript
interface A {}
interface B {}
type C = A | B
```

When possible, the converter rewrites it to inheritance, as the meaning should be the same, and both scalac and intellij behave quite a lot better.
```typescript
interface C {}
interface A extends C {}
interface B extends C {}
```

So what I hadn't thought about is that when `A` and `B` are mapped to types in scalajs-dom, these relationships are lost.
It would be easy to skip the [transformation](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/transforms/UnionToInheritance.scala) in the pipeline when rewriting types.

`useScalaJsDomTypes` is a bit half baked, as you have noticed, as I really just hacked it up to support the react flavours.
