### ISSUE TITLE
converter ignores custom ivy cache setting in sbt

### ISSUE THREAD

**Issue by an-tex** [ScalablyTyped/Converter#156]
When running `sbt -Dsbt.ivy.home=customCacheFolder` this [setting](https://www.scala-sbt.org/1.x/docs/Library-Management.html#Ivy+Home+Directory) is not being used for the artifacts generated by the converter, instead the default `$HOME/.ivy2/local` is [used](https://github.com/ScalablyTyped/Converter/blob/master/utils/src/main/scala/org/scalablytyped/converter/internal/constants.scala#L19).

This leads to assembly errors, e.g.
```
[error] sbt.librarymanagement.ResolveException: Error downloading org.scalablytyped:fortawesome__free-brands-svg-icons_sjs0.6_2.12:5.13.0-e66cf0
 [error]   Not found
 [error]   Not found
 [error]   not found: /builds/XXX/default/sbt-cache/ivy/local/org.scalablytyped/fortawesome__free-brands-svg-icons_sjs0.6_2.12/5.13.0-e66cf0/ivys/ivy.xml
```

This setting can be read from `ivyPaths.value.ivyHome`

In my case I'm using a gitlab runner with cached folders to speed up runs, but the cached folder must reside inside the cloned repo (and not in users home).

**Comment by oyvindberg** [comment]
Aha! I had a feeling this might show up, since I was too lazy to figure out where sbt found that. Would you mind giving it a shot with a PR? Start here probably https://github.com/ScalablyTyped/Converter/blob/master/sbt-converter/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedConverterPlugin.scala#L106 and similar for ScalablyTypedConverterExternalNpmPlugin.scala

**Comment by an-tex** [comment]
Thanks for the directions, I’ll create a PR next week!
