### ISSUE TITLE
`stUseScalaJsDom := false` also behaves like "`stUseScalaJsStdLib := false`"

### ISSUE THREAD

**Issue by armanbilge** [ScalablyTyped/Converter#372]
In https://github.com/typelevel/fs2/pull/2681 I wanted to remove the scalajs-dom dependency from the Node.js facade in fs2.

However, I was surprised that setting `stUseScalaJsDom := false` also swapped all the Scala.js standard library types for ST facade types. E.g. `js.Error` became `std.Error`, etc. I feel like this should be a separate option?

**Comment by oyvindberg** [comment]
Hey there, thanks for the report.

I do agree that it's somewhat deceivingly named. I designed it as a switch between the ST/TS universe and the Scala.js universe, and it didn't really occur to me at all that it crossed library boundaries.

In fact some other Javascript types defined in Scala.js proper are unconditionally used for translation, you can see most of them [ImportType](https://github.com/ScalablyTyped/Converter/blob/master/importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/ImportType.scala#L33). 

I'd happily accept a PR which moves pairs of type definitions from [ScalaJsDomNames](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/ScalaJsDomNames.scala) to there.

Otherwise I'll get to it eventually, but it'll take some time due to me having much less time available.

**Comment by armanbilge** [comment]
Thanks for fixing!!
