### ISSUE TITLE
Varargs are passed as scala collection instance

### ISSUE THREAD

**Issue by fdietze** [ScalablyTyped/Converter#392]
sbt-converter version: `1.0.0-beta36+44-f18e6850-SNAPSHOT`

I just tried to use firebase firestore and got a runtime error, because passing varargs to a facade actually passes the instance of a scala collection:

![2021-12-20_19-44-59_852x325](https://user-images.githubusercontent.com/1186516/146817187-c9cfb9be-e539-45b1-862b-50d476e28f8d.png)

The typescript type signature:

https://github.com/firebase/firebase-js-sdk/blob/532b3cd939c5a2c13987a21e38a0a121c5dfca04/packages/firestore/src/lite-api/reference.ts#L327

```typescript
export function collection(
  firestore: Firestore,
  path: string,
  ...pathSegments: string[]
): CollectionReference<DocumentData>;
```

The generated facade:

```scala
@scala.inline
def collection(
  firestore: typings.firebaseFirestore.mod.Firestore,
  path: java.lang.String,
  pathSegments: java.lang.String*
): typings.firebaseFirestore.mod.CollectionReference[typings.firebaseFirestore.mod.DocumentData] = (
  typings.firebaseFirestore.mod.^.asInstanceOf[js.Dynamic].applyDynamic("collection")(
    firestore.asInstanceOf[js.Any],
    path.asInstanceOf[js.Any],
    pathSegments.asInstanceOf[js.Any]
  )
).asInstanceOf[typings.firebaseFirestore.mod.CollectionReference[typings.firebaseFirestore.mod.DocumentData]]
```

This might be a scalajs issue, but I didn't find much about it. The documentation says:

> Methods can have varargs, denoted by * like in regular Scala. They map to JavaScript varargs, i.e., the method is called with more arguments.

(https://www.scala-js.org/doc/interoperability/facade-types.html)

**Comment by oyvindberg** [comment]
Oh wow, you're right. It's doesn't forward the parameters as varargs! I'll fix that soon :)

Meanwhile you can copy/paste that problematic fragment and add `:_*` within applyDynamic

**Comment by fdietze** [comment]
Thank you! I was already looking for workarounds :)

**Comment by oyvindberg** [comment]
Of course there was a twist to this, see https://github.com/ScalablyTyped/Converter/pull/394/files . 

If you have the chance to `publishLocal` that branch and test the snapshot that would be awesome

**Comment by fdietze** [comment]
Amazing, it works! Thank you so much!

The generated facade now looks like this:

```scala
def doc(
  firestore: typings.firebaseFirestore.mod.Firestore,
  path: java.lang.String,
  pathSegments: java.lang.String*
): typings.firebaseFirestore.mod.DocumentReference[typings.firebaseFirestore.mod.DocumentData] = (
  typings.firebaseFirestore.mod.^.asInstanceOf[js.Dynamic].applyDynamic("doc")(
    (scala.List(firestore.asInstanceOf[js.Any], path.asInstanceOf[js.Any]))
    .`++`(
      pathSegments.asInstanceOf[scala.Seq[js.Any]]) :_*)
).asInstanceOf[typings.firebaseFirestore.mod.DocumentReference[typings.firebaseFirestore.mod.DocumentData]]
```
This call
`val document = doc(db, "topics", "other", "something")`

is fastopt compiled to this javascript code:

```javascript
  var firestore = this.db__Ltypings_firebaseFirestore_mod_Firestore();
  var array = ["other", "something"];
  var pathSegments = new $c_sjsr_WrappedVarArgs(array);
  var $$x1 = $i_$0040firebase$002ffirestore;
  $m_s_package$();
  var array$1 = [firestore, "topics"];
  var elems = new $c_sjsr_WrappedVarArgs(array$1);
  var this$9 = $m_sci_Nil$().prependedAll__sc_IterableOnce__sci_List(elems);
  var seq = this$9.appendedAll__sc_IterableOnce__sci_List(pathSegments);
  var document = $$x1.doc(...$m_sjsr_Compat$().toJSVarArgsImpl__sci_Seq__sjs_js_Array(seq));
```

Since the generated code is using a Scala `List`, I guess the fullOpt compiler is not able to inline everything as desired. Maybe using a plain `js.Array` instead could help here?

For reference, the `.toJSVarArgsImpl__sci_Seq__sjs_js_Array` function:

```javascript
$c_sjsr_Compat$.prototype.toJSVarArgsImpl__sci_Seq__sjs_js_Array = (function(seq) {
  if ((seq instanceof $c_sjsr_WrappedVarArgs)) {
    var x2 = $as_sjsr_WrappedVarArgs(seq);
    return x2.sjsr_WrappedVarArgs__f_scala$scalajs$runtime$WrappedVarArgs$$array
  } else {
    var result = [];
    seq.foreach__F1__V(new $c_sjsr_AnonFunction1(((this$1, result$1) => ((x$2) => $uI(result$1.push(x$2))))(this, result)));
    return result
  }
});
```

and `WrappedVarArgs`:

https://github.com/scala-js/scala-js/blob/0708917912938714d52be1426364f78a3d1fd269/library/src/main/scala-new-collections/scala/scalajs/runtime/WrappedVarArgs.scala

**Comment by oyvindberg** [comment]
Thanks for trying and for doing that writeup @fdietze .

This part of the encoding is surprisingly tricky. Specifically, we're talking about "static" things, as opposed to methods in traits and classes. That's another can of worms.

Methods like this *need* to exist in some scope which doesn't inherit from `js.Object` because non-Javascript members like companion objects needs to go adjacent to it. Not doing that would require us to split libraries into two parallel namespaces.

That scope is either a package object or as a top-level member in a package (for scala 2 and 3, respectively), or in an `object`. 

You would think it would work to just define a `@js.native def` inside that scope, but it does the wrong thing with `this` - it has no receiver, in Javascript terms. See #256 

So that leaves us with `inline` pure Scala methods which I've called "forwarders", which uses `js.Dynamic` and casts to do the same thing. This has the benefit that we can invent a receiver object. It should also be erased in final emitted Javascript code.

And then there is this issue, with varargs. Because of limitations in Scala's handling of varargs, it seems impossible to "forward" both named parameters and repeated parameters into `js.Dynamic#applyDynamic` without building up a sequence to use as a middleman. 

I experimented with emitting traits with a more suitable signature to avoid the allocation, but then bumped into a problem where you can't just take a reference to the global scope. `Loading the global scope as a value (anywhere but as the left-hand-side of a `.`-selection) is not allowed.`

Pff, so to sum it up, I'll just go with this, allocations and all. Any further effort spent on this should be to work with upstream to find a way to avoid the forwarders at all.

**Comment by oyvindberg** [comment]
also re:
> Since the generated code is using a Scala List, I guess the fullOpt compiler is not able to inline everything as desired. Maybe using a plain js.Array instead could help here?

You need a subtype of `scala.Seq` or `Array` to use varargs syntax, so it doesn't seem to work with `js.Array`
```
[error] 31 |  (js.Dynamic.global.applyDynamic("setTimeout")(foo*)).asInstanceOf[Timeout]
[error]    |                  [error]    | Found:    (foo : scala.scalajs.js.Array[scalajs.js.Any])
[error]    | Required: Seq[scala.scalajs.js.Any] | Array²[? <: scala.scalajs.js.Any]
[error]    |
[error]    | where:    Array  is a class in package scala.scalajs.js
[error]    |           Array² is a class in package scala
```

**Comment by fdietze** [comment]
Makes sense, thank you for your work!
