### ISSUE TITLE
ModuleNotFoundError in scalajs-bundler bundling stage

### ISSUE THREAD

**Issue by nkgm** [ScalablyTyped/Converter#417]
Generated typings for `@floating-ui/react-dom` (0.4.3)

Upon inclusion webpack complains:

```console
[info] Writing module entry point for myproject-fastopt-entrypoint.js
[info] Building webpack library bundles for myproject-fastopt in myproject/target/streams/_global/_global/_global/streams/fastOptJS-webpack-libraries
[info] Writing scalajs.webpack.config.js
[error] ModuleNotFoundError: Module not found: Error: Can't resolve '@floating-ui/react-dom/src/types' in 'myproject/target/scala-2.13/scalajs-bundler/main'
```

The offender:

```scala
// typings/floatingUIReactDom/typesMod.scala
@JSImport("@floating-ui/react-dom/src/types", JSImport.Namespace)
@js.native
val ^ : js.Any = js.native
```

```console
$ tree node_modules/@floating-ui/react-dom
node_modules/@floating-ui/react-dom
├── README.md
├── dist
│   ├── floating-ui.react-dom.cjs
│   ├── floating-ui.react-dom.esm.js
│   ├── floating-ui.react-dom.esm.min.js
│   ├── floating-ui.react-dom.js
│   └── floating-ui.react-dom.min.js
├── index.d.ts
├── package.json
└── src
    ├── index.d.ts
    ├── types.d.ts
    └── utils
        └── deepEqual.d.ts

```

Only discovered the issue when I made the typings into a separate library project and included a reference into my main project (virtually no code changes). Before that, the typings were part of the main project and the issue went unnoticed as I never needed to import or refer to `typings.floatingUIReactDom.typesMod.^`, though later on (while investigating) I tried `console.log(typings.floatingUIReactDom.typesMod.^)` and sure enough it triggered the error.

**Comment by oyvindberg** [comment]
Hi there.

Thanks for the report. This is a problem I've definitely seen before. the problem is that this is valid typescript code:
```typescript
import {autoPlacement} from '@floating-ui/react-dom/src/types'

console.warn(autoPlacement)
```

It'll compile:
```
tsc tester.tsx  --lib es2015,dom
```

and fail in the same fashion. 

So the issue then is that ST currently doesn't check if there are `.js` files corresponding to the modules. The reason it doesn't is that often you don't have `.js` files. For instance you may only have a `@types/...` package to translate. And it would also be confusing if the output of the converter would vary depending on if you had those available or not. I'm really not sure what to do about this.

## fix

In ST packages generally correspond to modules. You want to import from the top-level module of that library, `typings.floatingUiReactDom.mod`. I've tried to explain it somewhat here https://scalablytyped.org/docs/usage#anatomy-of-a-typing-library . 

If you distribute typings as a library you can delete modules like `typings.floatingUiReactDom.typesMod`.

**Comment by oyvindberg** [comment]
I should probably link in https://github.com/ScalablyTyped/Converter/issues/367 as well

**Comment by nkgm** [comment]
Had to tippy toe around the offending import through trial and error with a couple alternative packages as not everything is available through the `mod` package. Thanks for taking the time to properly explain this on here and gitter. Finally got some time to go through the material and everything makes more sense already.
