### ISSUE TITLE
Parser failure in @material/web

### ISSUE THREAD

**Issue by FabioPinheiro** [ScalablyTyped/Converter#572]
I wanted to use the new material design 3.
But I'm getting this error

```sbt
[error] Phase1ReadTypescript.scala:72 message Couldn't parse: Parse error at 128.75 end of input expected [file => ../internal/controllers/shared.d.ts, thread => 214, project => did, ms => 4682, phase => typescript, id => @material/web]com.olvind.logging.Logger$LoggedException: Couldn't parse: Parse error at 128.75 end of input expected
[error] 	at com.olvind.logging.Logger$LoggingOps$.fatal$extension(Logger.scala:178)
[error] 	at org.scalablytyped.converter.internal.importer.Phase1ReadTypescript.$anonfun$apply$4(Phase1ReadTypescript.scala:72)
[error] 	at org.scalablytyped.converter.internal.importer.Lazy$$anon$1.get(Lazy.scala:30)
...
```

I was trying to find out or have a idea of what the problem may be.
I don't know where to start. Also can't fine any file `../internal/controllers/shared.d.ts`

**Comment by oyvindberg** [comment]
parser failure is fixed in newest master now, at least for version 1.0.0.
There were some compile failures which you can fixup manually if you use the sourcegen route - a bunch of overrides you can delete. the computation for figuring out of `override` is needed is surprisingly hard in such deep hierarchies of traits and classes.
