### ISSUE TITLE
Work on parser

### ISSUE THREAD

**Issue by oyvindberg** [ScalablyTyped/Converter#66]
There are still a bunch of files which dont parse (run `SuchTestMuchFail` to see which), we should fix those.

Ideally we would extend `TsTypeFormatter` to print all of Typescript so we can assert that all files can be printed again with the same contents (modulo formatting) for a super awesome test suite. There is a lot of work remaining for that, however.

There is also the option of somehow using Typescript's own parser and outputting to json as part of a build pipeline. It's significantly more complex, but would allow us to delete a lot of code!

Another option is to work on parser performance, perhaps in the shape of a rewrite to fastparse 2

**Comment by rossoha** [comment]
@oyvindberg Have you considered to use smt like  https://github.com/sjrd/scalatscomp?

**Comment by oyvindberg** [comment]
Unbelievable, I hadn't seen that. It's not directly useful given that it doesn't look like it compiles and it's a few years old. Typescript has changed *a lot* in three years. But fascinating work anyways

**Comment by rossoha** [comment]
@oyvindberg 
I've been thinking a lot about this issue and tried different implementations.     
I'll write here the list of solutions that in my opinion most promising: 

### 1. Use fastparse 2:
**Advantages**: 
- after parsing we have AST that looks like we need. 

**Downsides**: 
- hard to maintain for new Typescript releases
- might be still slow.  

### 2. Use ANTL4:
**Advantages**: 
    - Should be faster than fastparse 2 

**Downsides**: 
- To get Scala AST you need to traverse through all nodes using Java API. 
- Need to updated grammar (current impl for version 1.6), and keep it up to date. 

### 3. Use typescript parser: 
**Advantages**: 
-  The fastest implementation out of the box (there is Rust impl that might be faster, but it's more about language performance that about parsing speed
- No need to update parser for new versions (only AST implementation that will not change dramatically)	

**Downsides**: 
- Make mapping from JSON to scala AST fast to make the entire process fast enough.  
- Need to create Scala AST that is not easy due to a lot of union types in Typescript. 





I've been playing with all of them, and the last one looks most promising to me. But two problems there still need to be addressed.
Here is an example implementation that allows you to call typescript and map results AST JSON subset to Scala. 
[https://github.com/rossoha/typescript-wrapper](https://github.com/rossoha/typescript-wrapper)

You can warm-up JVM and parsing "typescript.d.ts" will take less than 100 ms due to JIT,  but mapping it to JSON will not be less than 250 ms. But taking into account file size it should be quite a good result.

**Comment by oyvindberg** [comment]
Fascinating, there has been some development there that I didn't know about! :)

Performance is (predictably) much better.

Your two downsides are not actually that bad:

We already have complete definitions of the typescript trees in javascript. I copy/pasted/adapted a few from for instance [Node.scala](https://github.com/ScalablyTyped/Distribution/blob/master/t/typescript/src/main/scala/typings/typescript/mod/Node.scala), and you can just cast directly to those traits. We can do a manual pass, or hack together a graalvm flavour to generate them automatically. Using these we don't have to go through json. See https://github.com/ScalablyTyped/typescript-wrapper/commit/6d3505d79185739737efdab1d447619b3238e8aa

I have two potential deal breakers I'd like to investigate right away
- can we extract comments?
- what does it take for a user to run this graalvm polyglot thing? can it run in a random persons sbt?

**Comment by oyvindberg** [comment]
Also the thing I'm most excited about when it comes to using typescript itself is to possibility of using more functionality than just the parser. For instance if we could delete the implementation of the module system or mapped types, that would be an even bigger win

**Comment by oyvindberg** [comment]
It's much, much slower than on node, at least before it's properly warmed up, which seemed to take minutes. I ran it on all of DefinitelyTyped to test.

Starting from cold on a rather big file, `DefinitelyTyped/types/activex-libreoffice/index.d.ts`, the current parser combinator based parser spent 4335 ms, while typescript on graalvm spent 13850 ms

**Comment by oyvindberg** [comment]
Say what. I get ten seconds even on node?!

```bash
$ cat run.js 
const ts = require('typescript')
const fs = require('fs')
ts.createSourceFile(process.argv[0], fs.readFileSync(process.argv[0]).toString(), "99")

$ time node run.js /home/olvind/st/DefinitelyTyped/types/activex-libreoffice/index.d.ts

real	0m10,923s
user	0m14,967s
sys	0m0,775s
```

**Comment by oyvindberg** [comment]
Maybe it's IO? Just running typescript is plenty fast, and that probably does much more

```bash
$ yarn add typescript @types/activex-libreoffice
$ time node_modules/.bin/tsc node_modules/@types/activex-libreoffice/index.d.ts > /dev/null

real	0m2,290s

**Comment by oyvindberg** [comment]
There is a way here, [dukat](https://github.com/kotlin/dukat) doesn't have the same performance problem. It goes through `ts.createLanguageService` -> `getProgram()` -> `getSourceFile()` instead, with a custom `ts.LanguageServiceHost`.

**Comment by rossoha** [comment]
>  There is a way here, dukat 

Wow!  It's fantastic. They use LanguageService to find all dependencies for Js/Ts files. But from what I've found/understand they use it only for generating `.d.ts` files of the standard library and maybe for raw files that are not got to DefinitelyTyped. What they doing next, is fantastic! They are map `.d.ts` to Kotlin wrappers... nothing fascinating right!? But most fascinating is How they doing it! They use ATLR4 grammar for the `Web IDL` standard. This is interface description language (IDL),  and starting from typescript version 3.1 `d.ts` preserves this standard.  
That's why they have good performance. And the complexity for them is to write mappers for ANTLR generated AST. And use ANTLR visitor to map it to their definitions. This is super cool and should be super fast (cause there is no cross-language calling, only IO operations for `.d.ts` read and `.kt` write). 
_I've been thinking about ANTLR  for a typescript, but with WebIDL it's much easier_
[WebIDL](https://www.w3.org/TR/WebIDL/)

**Comment by oyvindberg** [comment]
I don't see why Web IDL is applicable really. 

Typescript generates their stdlib definitions based on it, but we already have a pretty good and lossless conversion of those. Is there anything else useful described with Web IDL?

> That's why they have good performance. And the complexity for them is to write mappers for ANTLR generated AST

They are apparently creating an everything to Kotlin converter, where IDL is one of the input formats. They still need to implement everything we have here for Typescript except what they can offload to the compiler itself. The pipeline is actually long, in that they use protobuf to serialize trees and move them from node to the jvm, AFAIU
